export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';

export const FETCH_CATALOGS_START = 'FETCH_CATALOGS_START';
export const FETCH_CATALOGS_SUCCESS = 'FETCH_CATALOGS_SUCCESS';
export const FETCH_CATALOGS_FAIL = 'FETCH_CATALOGS_FAIL';
